[project]
name = "auto-sora"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.69.0",
    "black>=25.9.0",
    "dotenv>=0.9.9",
    "python-dotenv>=1.0.0",
    "streamlit>=1.31.0",
    "watchdog>=6.0.0",
]
